# Generated by Django 2.2.1 on 2020-02-26 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ptt',
            name='author',
            field=models.TextField(default='a'),
        ),
        migrations.AlterField(
            model_name='ptt',
            name='target',
            field=models.TextField(default='t'),
        ),
    ]
