# Generated by Django 2.2.1 on 2020-02-26 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptt', '0002_auto_20200226_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ptt',
            name='created',
        ),
        migrations.RemoveField(
            model_name='ptt',
            name='last_modify_date',
        ),
    ]
