# Generated by Django 2.2.1 on 2020-02-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt', '0003_auto_20200226_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Try',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.TextField()),
                ('market', models.TextField()),
            ],
            options={
                'db_table': 'try',
            },
        ),
    ]
