# Generated by Django 2.2.1 on 2020-02-26 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptt', '0004_try'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='ptt',
            table='ptt_db',
        ),
    ]
