# Generated by Django 2.2.1 on 2020-02-28 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptt', '0005_auto_20200226_1443'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Try',
        ),
    ]
