# Generated by Django 2.2.1 on 2020-02-28 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt', '0006_delete_try'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stockID', models.TextField()),
                ('stock', models.TextField()),
                ('market', models.TextField()),
            ],
            options={
                'db_table': 'Stock_db',
            },
        ),
        migrations.AlterModelTable(
            name='ptt',
            table='Ptt_db',
        ),
    ]
