# Generated by Django 2.2.1 on 2020-02-28 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptt', '0007_auto_20200228_0424'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'managed': False},
        ),
    ]
