# Generated by Django 2.2.1 on 2020-02-28 05:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt', '0008_auto_20200228_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptt',
            name='date',
            field=models.DateTimeField(default=datetime.date(2020, 12, 30)),
        ),
        migrations.AddField(
            model_name='ptt',
            name='dislike',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ptt',
            name='label',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='ptt',
            name='like',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ptt',
            name='neutral',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ptt',
            name='title',
            field=models.TextField(default='default'),
        ),
        migrations.AddField(
            model_name='ptt',
            name='url',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='ptt',
            name='author',
            field=models.TextField(default='default'),
        ),
        migrations.AlterField(
            model_name='ptt',
            name='target',
            field=models.TextField(default='default'),
        ),
    ]
