# Generated by Django 2.2.1 on 2020-02-28 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptt', '0009_auto_20200228_0510'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={},
        ),
    ]
