# Generated by Django 2.2.1 on 2020-02-29 06:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt', '0010_auto_20200228_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='market',
        ),
        migrations.RemoveField(
            model_name='stock',
            name='stock',
        ),
        migrations.AddField(
            model_name='stock',
            name='close',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='stock',
            name='date',
            field=models.DateTimeField(default=datetime.date(2020, 12, 30)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stockID',
            field=models.TextField(default='default'),
        ),
    ]
