# Generated by Django 2.2.1 on 2020-07-12 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt', '0011_auto_20200229_0619'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptt',
            name='roi_3',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='ptt',
            name='roi_overall',
            field=models.FloatField(default=0),
        ),
    ]
