# Generated by Django 2.2.1 on 2020-07-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptt', '0012_auto_20200712_0926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ptt',
            old_name='author',
            new_name='Author',
        ),
        migrations.RenameField(
            model_name='ptt',
            old_name='date',
            new_name='Date',
        ),
        migrations.RenameField(
            model_name='ptt',
            old_name='dislike',
            new_name='Dislike',
        ),
        migrations.RenameField(
            model_name='ptt',
            old_name='label',
            new_name='Label',
        ),
        migrations.RenameField(
            model_name='ptt',
            old_name='like',
            new_name='Like',
        ),
        migrations.RenameField(
            model_name='ptt',
            old_name='neutral',
            new_name='Neutral',
        ),
        migrations.RenameField(
            model_name='ptt',
            old_name='roi_3',
            new_name='ROI_3d',
        ),
        migrations.RenameField(
            model_name='ptt',
            old_name='target',
            new_name='Target',
        ),
        migrations.RenameField(
            model_name='ptt',
            old_name='title',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='ptt',
            old_name='url',
            new_name='Url',
        ),
        migrations.RemoveField(
            model_name='ptt',
            name='roi_overall',
        ),
    ]
