# Generated by Django 2.2.1 on 2020-07-12 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt', '0013_auto_20200712_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptt',
            name='ROI_overall',
            field=models.FloatField(default=0),
        ),
    ]
