# Generated by Django 2.2.1 on 2020-07-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ptt', '0014_ptt_roi_overall'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ptt',
            old_name='ROI_3d',
            new_name='ROI_1d',
        ),
    ]
