# Generated by Django 2.2.1 on 2020-07-25 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ptt', '0015_auto_20200712_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='ptt',
            name='Price',
            field=models.FloatField(default=0),
        ),
    ]
